/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegiotps;

import Controladores.AlumnoJpaController;
import Controladores.CarnetJpaController;
import Controladores.ContactoJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Entidades.Alumno;
import Entidades.Carnet;
import Entidades.Contacto;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sun.java2d.pipe.SpanShapeRenderer;

/**
 *
 * @author PANCHY
 */
public class AlumnoForm extends javax.swing.JFrame {
    private String alumn;
    DefaultTableModel modelo;
    Alumno alumno;
    Carnet carnet;
    Contacto contacto;
    AlumnoJpaController CAlumno = new AlumnoJpaController();
    ContactoJpaController Ccontacto = new ContactoJpaController();
    CarnetJpaController Ccarnet= new CarnetJpaController();
    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yy");
   //hola
    

    /**
     * Creates new form Alumno
     */
    public AlumnoForm() {
        
     
        initComponents();
        mostrar();
                     this. btncrear . setEnabled (true);
                    this. btneditar. setEnabled (false);
                    this. btneliminar . setEnabled (false);

           CAlumno.ComboCarnet(cbcarnet);
          CAlumno.ComboContacto(cbcontacto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbcarnet = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbcontacto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtnombre = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtapellido = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdireccion = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtAlumno = new javax.swing.JTable();
        btncrear = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Carnet:");

        jLabel2.setText("Contacto:");

        jLabel3.setText("Nombre:");

        jScrollPane1.setViewportView(txtnombre);

        jLabel4.setText("Apellido:");

        jScrollPane2.setViewportView(txtapellido);

        jLabel5.setText("Fecha de Nacimiento:");

        try {
            txtfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Direccion:");

        jScrollPane3.setViewportView(txtdireccion);

        jtAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "id", "Carnet", "Contacto", "Nombre", "Apellido", "Fecha_Nacimento", "Direccion"
            }
        ));
        jtAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAlumnoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtAlumno);
        if (jtAlumno.getColumnModel().getColumnCount() > 0) {
            jtAlumno.getColumnModel().getColumn(0).setMinWidth(0);
            jtAlumno.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtAlumno.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("MANTENIMIENTO DE ALUMNO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btncrear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btneliminar))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbcontacto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbcarnet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtfecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btneditar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btncancelar)))))))
                .addGap(82, 82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbcarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear)
                    .addComponent(btneliminar)
                    .addComponent(btneditar)
                    .addComponent(btncancelar))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAlumnoMouseClicked
       
          try {  
                int indice =  this.jtAlumno.getSelectedRow ();
                if(indice >  - 1 )
                {
//                       cbcarnet.set (modelo.getValueAt (indice, 2 ).toString ());
//                       cbcontacto. setText (modelo.getValueAt (indice, 3 ).toString ());
                       txtnombre. setText (modelo.getValueAt (indice, 4 ).toString ());
                       txtapellido. setText (modelo.getValueAt (indice,  5).toString ());
                       txtfecha.setText(modelo.getValueAt (indice, 6 ).toString());
                       txtdireccion. setText (modelo.getValueAt (indice, 7 ).toString ());
                      alumno = (Alumno) this.jtAlumno.getValueAt(jtAlumno.getSelectedRow(), 0);
                       // this.cbEncargado.setSelectedItem ((modeloTable.getValueAt (indice, 4)));
                        this. btneditar . setEnabled ( true );
                    this. btneliminar . setEnabled ( true );
                    this. btncrear . setEnabled (false);
                }
         } catch( Exception e)
            {
                
            } 
// TODO add your handling code here:
    }//GEN-LAST:event_jtAlumnoMouseClicked

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
       
try {
        BigDecimal carnet = this.cbcarnet.getItemAt(cbcarnet.getSelectedIndex()).getIdCarnet(); 
        BigDecimal contacto = this.cbcontacto.getItemAt(cbcontacto.getSelectedIndex()).getIdContacto();
        String nombre = this.txtnombre.getText();
        String apellido = this.txtapellido.getText();
        Date fecha =format.parse(this.txtfecha.getText());
        String direccion = this.txtdireccion.getText();
        

        AlumnoJpaController ca = new AlumnoJpaController();
        Alumno c= new Alumno();
        Carnet n=new Carnet();
        Contacto co = new Contacto();
//c.setIdCarnet(Integer.parseInteger(idCarnet));
        n.setIdCarnet(carnet);
        c.setIdCarnet(n);
        co.setIdContacto(contacto);
        c.setIdContacto(co);
        c.setNombre(nombre);
        c.setApellido(apellido);
         c.setFechaNacimiento(fecha);
        c.setDireccion(direccion);
       
    ca.create(c);
   JOptionPane.showConfirmDialog(null,"Contacto ingresado correctamente");
    this.mostrar();
    }
    catch(Exception e)
        {
    JOptionPane.showConfirmDialog(null,"Error " + e.toString());
    }          

// TODO add your handling code here:
    }//GEN-LAST:event_btncrearActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
      int indice =  this. jtAlumno . getSelectedRow();       
        try{
            BigDecimal bigDecimalValue =  new  BigDecimal (modelo.getValueAt(indice, 1 ).toString());
            int opcion =  JOptionPane . showConfirmDialog ( null , " Está seguro que desea eliminar el Alumno " + bigDecimalValue . toString (), " Eliminar Alumno " , JOptionPane . YES_NO_OPTION );
            
            if (opcion == 0 ) {
                CAlumno . destroy(bigDecimalValue);
                
                this.btneliminar . setEnabled ( false );
                 this.mostrar(); 
            }
            else
            {
                
                this.Limpiar();
               
            }
            
        } catch ( NonexistentEntityException ex) {
            Logger.getLogger (AlumnoForm.class.getName()).log(Level.SEVERE , null , ex);
        }
         this.mostrar();         


// TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
       try{
                int opcion =  JOptionPane . showConfirmDialog ( null , " Está seguro que desea actualizar el contacto " , " Actualizar contacto " , JOptionPane . YES_NO_OPTION );
                if (opcion ==  0 )
                {
                    BigDecimal carnetb = this.cbcarnet.getItemAt(cbcarnet.getSelectedIndex()).getIdCarnet(); 
                  BigDecimal contactob = this.cbcontacto.getItemAt(cbcontacto.getSelectedIndex()).getIdContacto();
                  Carnet n=new Carnet();
                  Contacto co = new Contacto();
                  n.setIdCarnet(carnetb);
                  co.setIdContacto(contactob);
                   
                  alumno.setIdCarnet(n);
                  alumno.setIdContacto(co);
                    alumno. setNombre (txtnombre .getText());
                    alumno. setApellido (txtapellido .getText());
                    alumno.setFechaNacimiento(format.parse(txtfecha .getText()));
                    alumno. setDireccion (txtdireccion .getText());
                    CAlumno.edit(alumno);
                    mostrar();
                    this. btneditar . setEnabled ( false );
                    this. btneliminar . setEnabled ( false );
                    this. btncrear . setEnabled (true);
                    
                    this. Limpiar ();
                }
                else
                {
                    this. btncrear . setEnabled (true);
                    this. btneditar. setEnabled (false);
                    this. btneliminar . setEnabled (false);
                    this. Limpiar ();
                }
                
            } catch ( Exception e)     
             {

               JOptionPane.showMessageDialog ( null , e);
             } 
        

// TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
    Limpiar();
        this. btncrear . setEnabled (true);
                    this. btneditar. setEnabled (false);
                    this. btneliminar . setEnabled (false);

// TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlumnoForm().setVisible(true);
            }
        });
    }
    
    public void mostrar()
    {
    Object c []=null;
    modelo= (DefaultTableModel) this.jtAlumno.getModel();
    
    List < Alumno >  Lalumno  = CAlumno.findAlumnoEntities();
        for (int i = 0; i <Lalumno.size() ; i++) {
            modelo.addRow(c);
            modelo.setValueAt (Lalumno.get(i),i,0);
            modelo.setValueAt (Lalumno.get(i).getIdAlumno(),i,1);
            modelo.setValueAt(Lalumno.get(i).getIdCarnet(), i,2);
            modelo.setValueAt(Lalumno.get(i).getIdContacto(), i,3);
            modelo.setValueAt(Lalumno.get(i).getNombre(), i,4);
            modelo.setValueAt(Lalumno.get(i).getApellido(), i,5);
            modelo.setValueAt(Lalumno.get(i).getFechaNacimiento(), i,6);
             modelo.setValueAt(Lalumno.get(i).getDireccion(), i,7);
        }
        
        
        
        
    
        

    }
    
     public void Limpiar()
    {
    this.txtnombre.setText(" ");
     this.txtapellido.setText(" ");
       this.txtdireccion.setText(" ");
        this.txtfecha.setText(" ");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JComboBox<Entidades.Carnet> cbcarnet;
    private javax.swing.JComboBox<Contacto> cbcontacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtAlumno;
    private javax.swing.JTextPane txtapellido;
    private javax.swing.JTextPane txtdireccion;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JTextPane txtnombre;
    // End of variables declaration//GEN-END:variables
}
