/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegiotps;
import Controladores.*;
import Controladores.exceptions.NonexistentEntityException;
import java.util.List;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PANCHY
 */
public class CarnetForm extends javax.swing.JFrame {
    
    DefaultTableModel modelo;
    private String carnet;
   
    CarnetJpaController Ccarnet = new CarnetJpaController();
    Entidades.Carnet carnete;
  
    
    /**
     * Creates new form Carnet
     */
    public CarnetForm() {
        initComponents();
        mostrar();
    }

    CarnetForm(BigDecimal idCarnet, String carnet) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtcarnet = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btncrear = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jt1 = new javax.swing.JTable();
        btneditar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtcarnet);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("MANTENIMIETNO DE CARNET");

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        Jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "id", "Carnet"
            }
        ));
        Jt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jt1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Jt1);
        if (Jt1.getColumnModel().getColumnCount() > 0) {
            Jt1.getColumnModel().getColumn(0).setMinWidth(0);
            Jt1.getColumnModel().getColumn(0).setPreferredWidth(0);
            Jt1.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btncrear)
                        .addGap(28, 28, 28)
                        .addComponent(btneliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btneditar)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar)))
                .addGap(0, 136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(150, 150, 150))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear)
                    .addComponent(btneliminar)
                    .addComponent(btneditar)
                    .addComponent(btncancelar))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        
    
    try {
        String carne = this.txtcarnet.getText(); 

        CarnetJpaController ca = new CarnetJpaController();
        Entidades.Carnet c= new Entidades.Carnet();
//c.setIdCarnet(Integer.parseInteger(idCarnet));
        c.setCarnet(carne);
    ca.create(c);
   JOptionPane.showConfirmDialog(null,"Carnet ingresado correctamente");
    this.mostrar();
    }
    catch(Exception e)
        {
    JOptionPane.showConfirmDialog(null,"Error " + e.toString());
    }



// TODO add your handling code here:
    }//GEN-LAST:event_btncrearActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
      int indice =  this. Jt1 . getSelectedRow();       
        try{
            BigDecimal bigDecimalValue =  new  BigDecimal (modelo.getValueAt(indice, 1 ).toString());
            int opcion =  JOptionPane . showConfirmDialog ( null , " Está seguro que desea eliminar el carnet " + bigDecimalValue . toString (), " Eliminar Alumno " , JOptionPane . YES_NO_OPTION );
             this.mostrar();
            if (opcion ==  0 ) {
                Ccarnet . destroy(bigDecimalValue);
                
                this.btneliminar . setEnabled ( false );
               
            }
            else
            {
                
                this.Limpiar();
               
            }
            
        } catch ( NonexistentEntityException ex) {
            Logger.getLogger (CarnetForm.class.getName()).log(Level.SEVERE , null , ex);
        }
         this.mostrar();
// TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void Jt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jt1MouseClicked
      try {  
                int indice =  this.Jt1.getSelectedRow ();
                if(indice >  - 1 )
                {
                       txtcarnet. setText (modelo.getValueAt (indice, 2 ) . toString ());
                      carnete = (Entidades.Carnet) this.Jt1.getValueAt(Jt1.getSelectedRow(), 0);
                       // this.cbEncargado.setSelectedItem ((modeloTable.getValueAt (indice, 4)));
                }
         } catch( Exception e)
            {
                
            }       
        
// TODO add your handling code here:
    }//GEN-LAST:event_Jt1MouseClicked

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
       
 try{
                int opcion =  JOptionPane . showConfirmDialog ( null , " Está seguro que desea actualizar al carnet " , " Actualizar carnet " , JOptionPane . YES_NO_OPTION );
                if (opcion ==  0 )
                {
                    carnete. setCarnet (txtcarnet .getText());
                    Ccarnet.edit(carnete);
                    mostrar();
                    this. btneditar . setEnabled ( false );
                    this. btneliminar . setEnabled ( false );
                    this. btncrear . setEnabled (true);
                    
                    this. Limpiar ();
                }
                else
                {
                    this. btncrear . setEnabled (true);
                    this. btneditar. setEnabled (false);
                    this. btneliminar . setEnabled (false);
                    this. Limpiar ();
                }
                
            } catch ( Exception e)     
             {

               JOptionPane.showMessageDialog ( null , e);
             }        
// TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
                    this. btncrear . setEnabled (true);
                    this. btneditar. setEnabled (false);
                    this. btneliminar . setEnabled (false);
                    Limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarnetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarnetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarnetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarnetForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarnetForm().setVisible(true);
            }
        });
    }
    
    public void mostrar()
    {
    Object c []=null;
    modelo= (DefaultTableModel) this.Jt1.getModel();
    
    List < Entidades.Carnet >  Lcarnet  = Ccarnet.findCarnetEntities();
        for (int i = 0; i <Lcarnet.size() ; i++) {
            modelo.addRow(c);
            
            modelo.setValueAt (Lcarnet.get(i),i,0);
            modelo.setValueAt (Lcarnet.get(i).getIdCarnet(),i,1);
            modelo.setValueAt(Lcarnet.get(i).getCarnet(), i,2);
        }
    
        

    }
    public void Limpiar()
    {
    this.txtcarnet.setText(" ");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jt1;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtcarnet;
    // End of variables declaration//GEN-END:variables
}
