/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegiotps;

import Controladores.CarnetJpaController;
import Controladores.GradoJpaController;
import Controladores.UsuariosJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Entidades.Grado;
import Entidades.Seccion;
import Entidades.Usuarios;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PANCHY
 */
public class GradoForm extends javax.swing.JFrame {
DefaultTableModel modelo;
GradoJpaController Cgrado = new GradoJpaController();
Grado grado;
    /**
     * Creates new form GradoForm
     */
    public GradoForm() {
        initComponents();
          Cgrado.ComboRol(cbseccion);
          mostrar();
         this.txtid.hide();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbseccion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbgrado = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtgrado = new javax.swing.JTable();
        btncrear = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtid = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seccion:");

        jLabel2.setText("Grado:");

        cbgrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto" }));

        Jtgrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "id", "Seccion", "Grado"
            }
        ));
        Jtgrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtgradoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Jtgrado);
        if (Jtgrado.getColumnModel().getColumnCount() > 0) {
            Jtgrado.getColumnModel().getColumn(0).setMinWidth(0);
            Jtgrado.getColumnModel().getColumn(0).setPreferredWidth(0);
            Jtgrado.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtid);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("MANTENIMIENTO DE GRADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btncrear)
                                        .addGap(39, 39, 39)
                                        .addComponent(btneliminar))
                                    .addComponent(cbseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbgrado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btneditar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbseccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbgrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear)
                    .addComponent(btneliminar)
                    .addComponent(btneditar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtgradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtgradoMouseClicked
        
 try {  
                int indice =  this.Jtgrado.getSelectedRow ();
                if(indice >  - 1 )
                {
                       txtid. setText (modelo.getValueAt (indice, 2 ) . toString ());
                      grado = (Entidades.Grado) this.Jtgrado.getValueAt(Jtgrado.getSelectedRow(), 0);
                       // this.cbEncargado.setSelectedItem ((modeloTable.getValueAt (indice, 4)));
                }
         } catch( Exception e)
            {
                
            } 
        // TODO add your handling code here:
    }//GEN-LAST:event_JtgradoMouseClicked

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
 try {
           BigDecimal seccion = this.cbseccion.getItemAt(cbseccion.getSelectedIndex()).getIdSeccion();
  String grado = (String) this.cbgrado.getSelectedItem();
        GradoJpaController ca = new GradoJpaController();
        Entidades.Grado c= new Entidades.Grado();
     Seccion m=new Seccion();
//c.setIdCarnet(Integer.parseInteger(idCarnet));
  m.setIdSeccion(seccion);
        c.setIdSeccion(m);
        c.setGrado(grado);
    ca.create(c);
   JOptionPane.showConfirmDialog(null,"Grado ingresado correctamente");
    this.mostrar();
    }
    catch(Exception e)
        {
    JOptionPane.showConfirmDialog(null,"Error " + e.toString());
    }        

// TODO add your handling code here:
    }//GEN-LAST:event_btncrearActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
       
        int indice =  this.Jtgrado. getSelectedRow();       
        try{
            BigDecimal bigDecimalValue =  new  BigDecimal (modelo.getValueAt(indice, 1 ).toString());
            int opcion =  JOptionPane . showConfirmDialog ( null , " Está seguro que desea eliminar el grado " + bigDecimalValue . toString (), " Eliminar Grado " , JOptionPane . YES_NO_OPTION );
            
            if (opcion == 0 ) {
                Cgrado.destroy(bigDecimalValue);
                
                this.btneliminar . setEnabled ( false );
                 this.mostrar(); 
            }
            else
            {
                
              
               
            }
            
        } catch ( NonexistentEntityException ex) {
            Logger.getLogger (ProfesorForm.class.getName()).log(Level.SEVERE , null , ex);
        }
         this.mostrar();
// TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
       try{
                int opcion =  JOptionPane . showConfirmDialog ( null , " Está seguro que desea actualizar el contacto " , " Actualizar contacto " , JOptionPane . YES_NO_OPTION );
                if (opcion ==  0 )
                {
                   BigDecimal seccion = this.cbseccion.getItemAt(cbseccion.getSelectedIndex()).getIdSeccion();
                  Seccion m=new Seccion();
                  m.setIdSeccion(seccion);
                   
                 String grad = this.cbgrado.getSelectedItem().toString();
                
                    
                      grado.setIdSeccion(m);
                      grado.setGrado(grad);
                    Cgrado.edit(grado);
                    mostrar();
                    this. btneditar . setEnabled ( false );
                    this. btneliminar . setEnabled ( false );
                    this. btncrear . setEnabled (true);
                    
                   
                }
                else
                {
                    this. btncrear . setEnabled (true);
                    this. btneditar. setEnabled (false);
                    this. btneliminar . setEnabled (false);
                   
                }
                
            } catch ( Exception e)     
             {

               JOptionPane.showMessageDialog ( null , e);
             } 
        
// TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradoForm().setVisible(true);
            }
        });
    }
    
     public void mostrar()
    {
    Object c []=null;
    modelo= (DefaultTableModel) this.Jtgrado.getModel();
    
    List < Entidades.Grado >  Lgrado  = Cgrado.findGradoEntities();
        for (int i = 0; i <Lgrado.size() ; i++) {
            modelo.addRow(c);
            
            modelo.setValueAt (Lgrado.get(i),i,0);
            
            modelo.setValueAt (Lgrado.get(i).getIdGrado(),i,1);
            modelo.setValueAt (Lgrado.get(i).getIdSeccion(),i,2);
            modelo.setValueAt(Lgrado.get(i).getGrado(), i,3);
        }
    
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtgrado;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JComboBox<String> cbgrado;
    private javax.swing.JComboBox<Seccion> cbseccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane txtid;
    // End of variables declaration//GEN-END:variables
}
