/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegiotps;

import Controladores.AlumnoJpaController;
import Controladores.ContactoJpaController;
import Controladores.MateriaJpaController;
import Controladores.ProfesorJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Entidades.Alumno;
import Entidades.Carnet;
import Entidades.Contacto;
import Entidades.Materia;
import Entidades.Profesor;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PANCHY
 */
public class ProfesorForm extends javax.swing.JFrame {
    ProfesorJpaController Cprofesor = new ProfesorJpaController();
     DefaultTableModel modelo;
       Profesor profesor;
    /**
     * Creates new form ProfesorForm
     */
    public ProfesorForm() {
   initComponents();
             Cprofesor.ComboMateria(cbmateria);
             mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtnombre = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Jtprofesor = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtapellido = new javax.swing.JTextPane();
        btncrear = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();
        txtdui = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtdireccion = new javax.swing.JTextPane();
        txtnit = new javax.swing.JFormattedTextField();
        cbmateria = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtnombre);

        jLabel1.setText("Nombre:");

        Jtprofesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "id", "Nombre", "Apellido", "Dui", "Nit", "Direccion", "Materia"
            }
        ));
        Jtprofesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtprofesorMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Jtprofesor);
        if (Jtprofesor.getColumnModel().getColumnCount() > 0) {
            Jtprofesor.getColumnModel().getColumn(0).setMinWidth(0);
            Jtprofesor.getColumnModel().getColumn(0).setPreferredWidth(0);
            Jtprofesor.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel2.setText("Apellido:");

        jScrollPane2.setViewportView(txtapellido);

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Dui:");

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        try {
            txtdui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Nit:");

        jLabel5.setText("Direccion:");

        jScrollPane5.setViewportView(txtdireccion);

        try {
            txtnit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-######-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Materia:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("MANTENIMIENTO DE PROFESOR");

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btncrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btneditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdui, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbmateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(162, 162, 162))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear)
                    .addComponent(btneliminar)
                    .addComponent(btneditar)
                    .addComponent(btncancelar))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtprofesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtprofesorMouseClicked
      try {  
                int indice =  this.Jtprofesor.getSelectedRow ();
                if(indice >  - 1 )
                {
//                       cbcarnet.set (modelo.getValueAt (indice, 2 ).toString ());
//                       cbcontacto. setText (modelo.getValueAt (indice, 3 ).toString ());
                       txtnombre. setText (modelo.getValueAt (indice, 2 ).toString ());
                       txtapellido. setText (modelo.getValueAt (indice,  3).toString ());
                       txtdui.setText(modelo.getValueAt (indice, 4 ).toString());
                       txtnit. setText (modelo.getValueAt (indice, 5 ).toString ());
                       txtdireccion. setText (modelo.getValueAt (indice, 6 ).toString ());
                      profesor = (Profesor) this.Jtprofesor.getValueAt(Jtprofesor.getSelectedRow(), 0);
                       // this.cbEncargado.setSelectedItem ((modeloTable.getValueAt (indice, 4)));
                        this. btneditar . setEnabled ( true );
                    this. btneliminar . setEnabled ( true );
                    this. btncrear . setEnabled (false);

                }
         } catch( Exception e)
            {
                
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_JtprofesorMouseClicked

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed

        try {
        
 
        String nombre = this.txtnombre.getText();
        String apellido = this.txtapellido.getText();
        String dui =this.txtdui.getText();
          String nit =this.txtnit.getText();
        String direccion = this.txtdireccion.getText();
         BigDecimal materia = this.cbmateria.getItemAt(cbmateria.getSelectedIndex()).getIdMateria();
        ProfesorJpaController ca = new ProfesorJpaController();
        Profesor c= new Profesor();
        Materia m=new Materia();
       
//c.setIdCarnet(Integer.parseInteger(idCarnet));

        c.setNombre(nombre);
        c.setApellido(apellido);
         c.setDui(dui);
         c.setNit(nit);
        c.setDireccion(direccion);
        m.setIdMateria(materia);
        c.setIdMateria(m);
       
    ca.create(c);
   JOptionPane.showConfirmDialog(null,"Contacto ingresado correctamente");
    this.mostrar();
    }
    catch(Exception e)
        {
    JOptionPane.showConfirmDialog(null,"Error " + e.toString());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_btncrearActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

      int indice =  this.Jtprofesor. getSelectedRow();       
        try{
            BigDecimal bigDecimalValue =  new  BigDecimal (modelo.getValueAt(indice, 1 ).toString());
            int opcion =  JOptionPane . showConfirmDialog ( null , " Está seguro que desea eliminar al profesor " + bigDecimalValue . toString (), " Eliminar Profesor " , JOptionPane . YES_NO_OPTION );
            
            if (opcion == 0 ) {
                Cprofesor.destroy(bigDecimalValue);
                
                this.btneliminar . setEnabled ( false );
                 this.mostrar(); 
            }
            else
            {
                
                this.Limpiar();
               
            }
            
        } catch ( NonexistentEntityException ex) {
            Logger.getLogger (ProfesorForm.class.getName()).log(Level.SEVERE , null , ex);
        }
         this.mostrar();

        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
 try{
                int opcion =  JOptionPane . showConfirmDialog ( null , " Está seguro que desea actualizar el contacto " , " Actualizar contacto " , JOptionPane . YES_NO_OPTION );
                if (opcion ==  0 )
                {
                   BigDecimal materia = this.cbmateria.getItemAt(cbmateria.getSelectedIndex()).getIdMateria();
                  Materia m=new Materia();
                  m.setIdMateria(materia);
                   
                 
                    profesor. setNombre (txtnombre .getText());
                    profesor. setApellido (txtapellido .getText());
                    profesor.setDui(txtdui.getText());
                    profesor.setNit(txtnit.getText());
                    profesor. setDireccion (txtdireccion .getText());
                     profesor.setIdMateria(m);
                    Cprofesor.edit(profesor);
                    mostrar();
                    this. btneditar . setEnabled ( false );
                    this. btneliminar . setEnabled ( false );
                    this. btncrear . setEnabled (true);
                    
                    this. Limpiar ();
                }
                else
                {
                    this. btncrear . setEnabled (true);
                    this. btneditar. setEnabled (false);
                    this. btneliminar . setEnabled (false);
                    this. Limpiar ();
                }
                
            } catch ( Exception e)     
             {

               JOptionPane.showMessageDialog ( null , e);
             } 
      

        // TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
       Limpiar();
        this. btncrear . setEnabled (true);
                    this. btneditar. setEnabled (false);
                    this. btneliminar . setEnabled (false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfesorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfesorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfesorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfesorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfesorForm().setVisible(true);
            }
        });
        
        
    }
    
      public void mostrar()
    {
    Object c []=null;
    modelo= (DefaultTableModel) this.Jtprofesor.getModel();
    
    List < Entidades.Profesor >  Lprofe  = Cprofesor.findProfesorEntities();
        for (int i = 0; i <Lprofe.size() ; i++) {
            modelo.addRow(c);
            modelo.setValueAt (Lprofe.get(i),i,0);
            modelo.setValueAt (Lprofe.get(i).getIdProfesor(),i,1);
            modelo.setValueAt(Lprofe.get(i).getNombre(), i,2);
            modelo.setValueAt(Lprofe.get(i).getApellido(), i,3);
            modelo.setValueAt(Lprofe.get(i).getDui(), i,4);
            modelo.setValueAt(Lprofe.get(i).getNit(), i,5);
            modelo.setValueAt(Lprofe.get(i).getDireccion(), i,6);
             modelo.setValueAt(Lprofe.get(i).getIdMateria(), i,7);
        }
        
        
    
        

    }
       public void Limpiar()
    {
    this.txtnombre.setText(" ");
     this.txtapellido.setText(" ");
       this.txtdireccion.setText(" ");
        this.txtnit.setText("");
         this.txtdui.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtprofesor;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JComboBox<Materia> cbmateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane txtapellido;
    private javax.swing.JTextPane txtdireccion;
    private javax.swing.JFormattedTextField txtdui;
    private javax.swing.JFormattedTextField txtnit;
    private javax.swing.JTextPane txtnombre;
    // End of variables declaration//GEN-END:variables
}
