/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegiotps;

import Controladores.AlumnoJpaController;
import Controladores.ProfesorJpaController;
import Controladores.UsuariosJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Entidades.Materia;
import Entidades.Profesor;
import Entidades.Rol;
import Entidades.Usuarios;
import java.math.BigDecimal;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PANCHY
 */
public class UsuarioFrom extends javax.swing.JFrame {
UsuariosJpaController Cusuario = new UsuariosJpaController();
Usuarios usuario;
     DefaultTableModel modelo;
    /**
     * Creates new form UsuarioFrom
     */
    public UsuarioFrom() {
         
        
        initComponents();
        
         Cusuario.ComboRol(cbrol);
         mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtnombre = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Jtusuario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtapellido = new javax.swing.JTextPane();
        btncrear = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();
        txtdui = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtusuario = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtclave = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        cbrol = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtnombre);

        jLabel1.setText("Nombre:");

        Jtusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "id", "Nombre", "Apellido", "Dui", "Usuario", "Clave"
            }
        ));
        Jtusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtusuarioMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Jtusuario);
        if (Jtusuario.getColumnModel().getColumnCount() > 0) {
            Jtusuario.getColumnModel().getColumn(0).setMinWidth(0);
            Jtusuario.getColumnModel().getColumn(0).setPreferredWidth(0);
            Jtusuario.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jLabel2.setText("Apellido:");

        jScrollPane2.setViewportView(txtapellido);

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Dui:");

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        try {
            txtdui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Usuario:");

        jLabel5.setText("Clave:");

        jScrollPane3.setViewportView(txtusuario);

        jScrollPane5.setViewportView(txtclave);

        jLabel6.setText("Rol:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("MANTENIMIENTO DE USUARIOS");

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btncrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btneliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btneditar)
                                .addGap(18, 18, 18)
                                .addComponent(btncancelar))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbrol, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdui, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(cbrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtdui, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear)
                    .addComponent(btneliminar)
                    .addComponent(btneditar)
                    .addComponent(btncancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtusuarioMouseClicked

         try {  
                int indice =  this.Jtusuario.getSelectedRow ();
                if(indice >  - 1 )
                {
//                       cbcarnet.set (modelo.getValueAt (indice, 2 ).toString ());
//                       cbcontacto. setText (modelo.getValueAt (indice, 3 ).toString ());
                       txtnombre. setText (modelo.getValueAt (indice, 2 ).toString ());
                       txtapellido. setText (modelo.getValueAt (indice,  3).toString ());
                       txtdui.setText(modelo.getValueAt (indice, 4 ).toString());
                       txtusuario. setText (modelo.getValueAt (indice, 5 ).toString ());
                       txtclave. setText (modelo.getValueAt (indice, 6 ).toString ());
                      usuario = (Usuarios) this.Jtusuario.getValueAt(Jtusuario.getSelectedRow(), 0);
                       // this.cbEncargado.setSelectedItem ((modeloTable.getValueAt (indice, 4)));
                        this. btneditar . setEnabled ( true );
                    this. btneliminar . setEnabled ( true );
                    this. btncrear . setEnabled (false);

                }
         } catch( Exception e)
            {
                
            }

        // TODO add your handling code here:
    }//GEN-LAST:event_JtusuarioMouseClicked

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
           try {
        
  BigDecimal rol = this.cbrol.getItemAt(cbrol.getSelectedIndex()).getIdRol();
        String nombre = this.txtnombre.getText();
        String apellido = this.txtapellido.getText();
        String dui =this.txtdui.getText();
          String usuario =this.txtusuario.getText();
        String clave = this.txtclave.getText();
        
        UsuariosJpaController ca = new UsuariosJpaController();
        Usuarios c= new Usuarios();
        Rol r=new Rol();
       
//c.setIdCarnet(Integer.parseInteger(idCarnet));
        r.setIdRol(rol);
        c.setIdRol(r);
        c.setNombre(nombre);
        c.setApellido(apellido);
         c.setDui(dui);
         c.setUsuario(usuario);
        c.setClave(clave);
        
       
       
    ca.create(c);
   JOptionPane.showConfirmDialog(null,"Usuario ingresado correctamente");
    this.mostrar();
    }
    catch(Exception e)
        {
    JOptionPane.showConfirmDialog(null,"Error " + e.toString());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btncrearActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
 
        int indice =  this.Jtusuario. getSelectedRow();       
        try{
            BigDecimal bigDecimalValue =  new  BigDecimal (modelo.getValueAt(indice, 1 ).toString());
            int opcion =  JOptionPane . showConfirmDialog ( null , " Está seguro que desea eliminar al usuario " + bigDecimalValue . toString (), " Eliminar Usuario " , JOptionPane . YES_NO_OPTION );
            
            if (opcion == 0 ) {
                Cusuario.destroy(bigDecimalValue);
                
                this.btneliminar . setEnabled ( false );
                 this.mostrar(); 
            }
            else
            {
                
                this.Limpiar();
               
            }
            
        } catch ( NonexistentEntityException ex) {
            Logger.getLogger (ProfesorForm.class.getName()).log(Level.SEVERE , null , ex);
        }
         this.mostrar();
      

        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed

 try{
                int opcion =  JOptionPane . showConfirmDialog ( null , " Está seguro que desea actualizar el usuario " , " Actualizar usuario " , JOptionPane . YES_NO_OPTION );
                if (opcion ==  0 )
                {
                   BigDecimal rol = this.cbrol.getItemAt(cbrol.getSelectedIndex()).getIdRol();
                  Rol r=new Rol();
                  r.setIdRol(rol);
               
                 usuario.setIdRol(r);
                    usuario. setNombre (txtnombre .getText());
                    usuario. setApellido (txtapellido .getText());
                    usuario.setDui(txtdui.getText());
                    usuario.setUsuario(txtusuario.getText());
                    usuario. setClave(txtclave .getText());
                     
                    Cusuario.edit(usuario);
                    mostrar();
                    this. btneditar . setEnabled ( false );
                    this. btneliminar . setEnabled ( false );
                    this. btncrear . setEnabled (true);
                    
                    this. Limpiar ();
                }
                else
                {
                    this. btncrear . setEnabled (true);
                    this. btneditar. setEnabled (false);
                    this. btneliminar . setEnabled (false);
                    this. Limpiar ();
                }
                
            } catch ( Exception e)     
             {

               JOptionPane.showMessageDialog ( null , e);
             }
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        Limpiar();
        this. btncrear . setEnabled (true);
                    this. btneditar. setEnabled (false);
                    this. btneliminar . setEnabled (false);

// TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioFrom().setVisible(true);
            }
        });
    }
    
       public void mostrar()
    {
    Object c []=null;
    modelo= (DefaultTableModel) this.Jtusuario.getModel();
    
    List < Entidades.Usuarios >  Luser  = Cusuario.findUsuariosEntities();
        for (int i = 0; i <Luser.size() ; i++) {
            modelo.addRow(c);
            modelo.setValueAt (Luser.get(i),i,0);
            modelo.setValueAt (Luser.get(i).getIdUsuario(),i,1);
            modelo.setValueAt(Luser.get(i).getNombre(), i,2);
            modelo.setValueAt(Luser.get(i).getApellido(), i,3);
            modelo.setValueAt(Luser.get(i).getDui(), i,4);
            modelo.setValueAt(Luser.get(i).getUsuario(), i,5);
            modelo.setValueAt(Luser.get(i).getClave(), i,6);
        }
        
        
    
        

    }
       public void Limpiar()
    {
    this.txtnombre.setText(" ");
     this.txtapellido.setText(" ");
       this.txtusuario.setText(" ");
        this.txtclave.setText(" ");
         this.txtdui.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtusuario;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JComboBox<Rol> cbrol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane txtapellido;
    private javax.swing.JTextPane txtclave;
    private javax.swing.JFormattedTextField txtdui;
    private javax.swing.JTextPane txtnombre;
    private javax.swing.JTextPane txtusuario;
    // End of variables declaration//GEN-END:variables
}
